[package]
authors = ["Chun-Kwong Wong <chunkwong.wong@gmail.com>"]
edition = "2021"
name = "kyvi"
version = "0.1.0"

[dependencies]
serde = {version = "1.0.210", features = ["derive"]}
serde_derive = "1.0.210"
threadpool = "1.8.1"
